### ISSUE TITLE
version 2

### ISSUE THREAD

**Issue by liampauling** [liampauling/betfair#234]
# todo

- [x] Remove all py2 support 😄 

- [x] Remove all threading from streaming (no more async_)

- [x] Better logging on streaming (send/errors etc.)

- [x] Fix #217 do we want to continue using ujson?

- [ ] Resources refactor, use data classes? attrs?

- [ ] #149 async compat? Transport class?

- [x] Return requests response

- [ ] pass requests kwargs (timeout / proxy etc)

- [x] Types / better doc strings

- [x] black formatting

https://pythonclock.org/

**Comment by cmorgan** [comment]
https://github.com/sqlalchemyorg/zimports is helpful as well!

**Comment by fingoldo** [comment]
Hi, great library Liam, thank you so much for it, why do you want to remove threading?

**Comment by liampauling** [comment]
To force users to handle the thread and required error handling, async results in many users not catching errors (often failing silently) and then wondering why.

**Comment by HMaker** [comment]
@liampauling was this version 2 project cancelled?

**Comment by liampauling** [comment]
No v2 was released but async was binned.
